spring.datasource.url=jdbc:mysql://localhost:3306/Employeemanagement
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.activemq.broker-url=vm://embedded?broker.persistent=false
spring.activemq.in-memory=true
spring.activemq.pooled=false

spring.jms.pub-sub-domain=false
spring.jms.listener.auto-startup=true

